### ISSUE TITLE
Semagrow throws http 500 internal server error on any query on Cassandra endpoint

### ISSUE THREAD

**Issue by stasinos** [semagrow/connector-cassandra#1]
Submitter: Stathis Grigoropoulos, via email

Steps to Reproduce:

install make
export CLIMATE1_BUILD_DIR=/yourpath/
export CLIMATE1_CASSANDRA_DATA_DIR=/yourpath/
git clone https://github.com/iaklampanos/bde-climate-1  /yourpath/
cd yourpath
make compose 
make ingest-file NETCDFFILE=/path/to/file/file
Optional: make clean-netcdf-all #to build java projects of giannis and antonis

Command
java -jar /<YourJavaProjectPath>/netcdf-cassandra/target/netcdf-cassandra-0.0.1-SNAPSHOT-jar-with-dependencies.jar -s -t 'wrf' -e http://localhost:8090/SemaGrow/sparql

Output

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.openrdf.query.QueryEvaluationException: <html><head><title>Apache Tomcat/7.0.52 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - Unsupported tuple expr type: class org.openrdf.query.algebra.Join</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Unsupported tuple expr type: class org.openrdf.query.algebra.Join</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52</h3></body></html>
    at org.openrdf.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:59)
    at gr.demokritos.iit.netcdf.cassandra.SemagrowToNetCDF.termSearch(SemagrowToNetCDF.java:130)
    at gr.demokritos.iit.netcdf.cassandra.Main.main(Main.java:205)
Caused by: org.openrdf.repository.RepositoryException: <html><head><title>Apache Tomcat/7.0.52 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - Unsupported tuple expr type: class org.openrdf.query.algebra.Join</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Unsupported tuple expr type: class org.openrdf.query.algebra.Join</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52</h3></body></html>
    at org.openrdf.http.client.HTTPClient.handleHTTPError(HTTPClient.java:953)
    at org.openrdf.http.client.HTTPClient.sendTupleQueryViaHttp(HTTPClient.java:718)
    at org.openrdf.http.client.HTTPClient.getBackgroundTupleQueryResult(HTTPClient.java:602)
    at org.openrdf.http.client.HTTPClient.sendTupleQuery(HTTPClient.java:367)
    at org.openrdf.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:52)
    ... 2 more

Troubleshooting/Testing Steps Attempted
Runt different search params, imported different files. Seems to be file independent .

**Comment by antru6** [comment]
The current version of Cassandra connector uses a slightly different metadata vocabulary, than this of the previous version. The user in his application used a docker build of a previous version of sevod-scraper, and as a result the connector wouldn't work because of invalid metadata. Therefore, we are now using Webhooks to trigger automated building of the docker repositories.
